/**
 * Tailwind config for production builds.
 *
 * Dev uses the Tailwind Play CDN (see each campaign's _layouts/base-*.html,
 * loaded only when `environment == "development"`). Production builds load the
 * compiled stylesheet generated by `npm run build:css`, which scans the
 * content globs below for the utility classes actually used in the templates.
 *
 * Mirrors the inline `tailwind.config` theme in the base layouts so compiled
 * output matches what dev renders.
 */
module.exports = {
  content: [
    './src/**/*.html',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
      colors: {
        'brand-primary': 'var(--brand-primary)',
        'brand-secondary': 'var(--brand-secondary)',
        'brand-accent': 'var(--brand-accent)',
        'surface-bg': 'var(--surface-bg)',
        'surface-card': 'var(--surface-card)',
        'surface-alt': 'var(--surface-alt)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-inverse': 'var(--text-inverse)',
      },
    },
  },
  plugins: [],
};
